/* tl-lang.js — diccionario compartido ES / DE (cabecera, riel, mapa, UI genérica).
   Cada módulo agrega sus propias claves con TL.i18n.extend({ es:{}, de:{} }). */
(function () {
  'use strict';
  TL.i18n.extend({
    es: {
      'app.title': 'TRUMPF · Market Atlas LATAM',
      'brand.sub': 'Werkzeugmaschinen · Prospección comercial',
      'intro.kicker': 'Werkzeugmaschinen · Prospección comercial',
      'intro.title': 'Market Atlas LATAM',
      'loader.data': 'Cargando datos',
      'loader.map': 'Preparando el globo',
      'loader.layers': 'Trazando capas',
      'loader.ready': 'Listo',
      'loader.offline': 'Sin conexión: el mapa base no está disponible',
      'nav.home': 'Volver al inicio',
      'nav.crm': 'Seguimiento',
      'nav.present': 'Presentación',
      'ui.language': 'Idioma',
      'ui.theme': 'Cambiar tema claro / oscuro',
      'ui.close': 'Cerrar',
      'ui.back': 'Volver',
      'ui.open': 'Abrir',
      'ui.copy': 'Copiar',
      'ui.copied': 'Copiado',
      'ui.all': 'Todos',
      'ui.none': 'Ninguno',
      'ui.clear': 'Limpiar',
      'ui.clearAll': 'Limpiar filtros',
      'ui.more': 'Ver más',
      'ui.less': 'Ver menos',
      'ui.showMore': 'Mostrar {n} más',
      'ui.loading': 'Cargando',
      'ui.soon': 'Pronto',
      'ui.unavailable': 'Este módulo no está disponible en esta versión.',
      'ui.noResults': 'Sin resultados',
      'ui.new': 'Nuevo',
      'ui.newAI': 'Nuevo · IA',
      'ui.sources': 'Fuentes',
      'ui.source': 'Fuente',
      'ui.print': 'Imprimir / PDF',
      'ui.previous': 'Anterior',
      'ui.next': 'Siguiente',
      'ui.yes': 'Sí',
      'ui.no': 'No',
      'ui.unknown': 'Sin dato',
      'ui.of': 'de',
      'ui.sortBy': 'Ordenar por',
      'ui.filters': 'Filtros',
      'ui.search': 'Buscar',
      'rail.aria': 'Vistas del atlas',
      'rail.clients': 'Clientes',
      'rail.reps': 'Representantes',
      'rail.competition': 'Competencia',
      'rail.radar': 'Radar',
      'rail.gtm': 'Go-to-Market LATAM',
      'rail.tour': 'Gira',
      'rail.method': 'Metodología',
      'rail.crm': 'Seguimiento',
      'panel.aria': 'Panel de contenido',
      'panel.toggle': 'Mostrar u ocultar el panel',
      'panel.expand': 'Ampliar o reducir el panel',
      'map.aria': 'Mapa interactivo de América Latina',
      'map.zoomIn': 'Acercar',
      'map.zoomOut': 'Alejar',
      'map.satellite': 'Vista satelital',
      'map.buildings3d': 'Vista 3D (inclinar)',
      'map.reset': 'Volver a la vista general',
      'map.attrib': 'Datos de mapa © OpenStreetMap · OpenFreeMap',
      'map.attribSat': 'Imagen © Esri, Maxar, Earthstar Geographics',
      'map.offlineHint': 'El mapa base requiere conexión; los datos siguen disponibles.',
      'map.subsidiary': 'Filial TRUMPF',
      'map.clickToOpen': 'Click para abrir la ficha',
      'map.clickCountry': 'Click para ver el país',
      'map.cluster': '{n} empresas',
      'tier.A': 'Tier A',
      'tier.B': 'Tier B',
      'tier.C': 'Tier C',
      'tier.A.long': 'Prioridad alta',
      'tier.B.long': 'Prioridad media',
      'tier.C.long': 'Prioridad base',
      'score.label': 'Puntaje',
      'potential.alto': 'Potencial alto',
      'potential.medio': 'Potencial medio',
      'potential.bajo': 'Potencial bajo',
      'potential.none': 'Sin evaluar',
      'kind.client': 'Cliente potencial',
      'kind.rep': 'Representante',
      'kind.opp': 'Oportunidad',
      'kind.country': 'País',
      'kind.city': 'Ciudad',
      'count.clients.one': '{n} empresa',
      'count.clients.other': '{n} empresas',
      'count.reps.one': '{n} representante',
      'count.reps.other': '{n} representantes',
      'toast.langDe': 'Sprache: Deutsch',
      'toast.langEs': 'Idioma: español',
      'err.generic': 'Algo no salió bien. Probá de nuevo.',
    },
    de: {
      'app.title': 'TRUMPF · Market Atlas LATAM',
      'brand.sub': 'Werkzeugmaschinen · Vertriebsatlas',
      'intro.kicker': 'Werkzeugmaschinen · Vertriebsatlas',
      'intro.title': 'Market Atlas LATAM',
      'loader.data': 'Daten werden geladen',
      'loader.map': 'Globus wird vorbereitet',
      'loader.layers': 'Ebenen werden gezeichnet',
      'loader.ready': 'Bereit',
      'loader.offline': 'Offline: Die Basiskarte ist nicht verfügbar',
      'nav.home': 'Zur Startansicht',
      'nav.crm': 'Nachverfolgung',
      'nav.present': 'Präsentation',
      'ui.language': 'Sprache',
      'ui.theme': 'Helles / dunkles Design umschalten',
      'ui.close': 'Schließen',
      'ui.back': 'Zurück',
      'ui.open': 'Öffnen',
      'ui.copy': 'Kopieren',
      'ui.copied': 'Kopiert',
      'ui.all': 'Alle',
      'ui.none': 'Keine',
      'ui.clear': 'Zurücksetzen',
      'ui.clearAll': 'Filter zurücksetzen',
      'ui.more': 'Mehr anzeigen',
      'ui.less': 'Weniger anzeigen',
      'ui.showMore': '{n} weitere anzeigen',
      'ui.loading': 'Wird geladen',
      'ui.soon': 'Bald',
      'ui.unavailable': 'Dieses Modul ist in dieser Version nicht verfügbar.',
      'ui.noResults': 'Keine Ergebnisse',
      'ui.new': 'Neu',
      'ui.newAI': 'Neu · KI',
      'ui.sources': 'Quellen',
      'ui.source': 'Quelle',
      'ui.print': 'Drucken / PDF',
      'ui.previous': 'Zurück',
      'ui.next': 'Weiter',
      'ui.yes': 'Ja',
      'ui.no': 'Nein',
      'ui.unknown': 'Keine Angabe',
      'ui.of': 'von',
      'ui.sortBy': 'Sortieren nach',
      'ui.filters': 'Filter',
      'ui.search': 'Suchen',
      'rail.aria': 'Ansichten des Atlas',
      'rail.clients': 'Kunden',
      'rail.reps': 'Vertriebspartner',
      'rail.competition': 'Wettbewerb',
      'rail.radar': 'Radar',
      'rail.gtm': 'Go-to-Market LATAM',
      'rail.tour': 'Reiseplanung',
      'rail.method': 'Methodik',
      'rail.crm': 'Nachverfolgung',
      'panel.aria': 'Inhaltsbereich',
      'panel.toggle': 'Bereich ein- oder ausblenden',
      'panel.expand': 'Bereich vergrößern oder verkleinern',
      'map.aria': 'Interaktive Karte von Lateinamerika',
      'map.zoomIn': 'Vergrößern',
      'map.zoomOut': 'Verkleinern',
      'map.satellite': 'Satellitenansicht',
      'map.buildings3d': '3D-Ansicht (neigen)',
      'map.reset': 'Zur Gesamtansicht',
      'map.attrib': 'Kartendaten © OpenStreetMap · OpenFreeMap',
      'map.attribSat': 'Bilder © Esri, Maxar, Earthstar Geographics',
      'map.offlineHint': 'Die Basiskarte benötigt eine Internetverbindung; die Daten bleiben verfügbar.',
      'map.subsidiary': 'TRUMPF Niederlassung',
      'map.clickToOpen': 'Klicken, um das Profil zu öffnen',
      'map.clickCountry': 'Klicken, um das Land zu öffnen',
      'map.cluster': '{n} Unternehmen',
      'tier.A': 'Stufe A',
      'tier.B': 'Stufe B',
      'tier.C': 'Stufe C',
      'tier.A.long': 'Hohe Priorität',
      'tier.B.long': 'Mittlere Priorität',
      'tier.C.long': 'Basispriorität',
      'score.label': 'Bewertung',
      'potential.alto': 'Hohes Potenzial',
      'potential.medio': 'Mittleres Potenzial',
      'potential.bajo': 'Geringes Potenzial',
      'potential.none': 'Nicht bewertet',
      'kind.client': 'Potenzieller Kunde',
      'kind.rep': 'Vertriebspartner',
      'kind.opp': 'Chance',
      'kind.country': 'Land',
      'kind.city': 'Stadt',
      'count.clients.one': '{n} Unternehmen',
      'count.clients.other': '{n} Unternehmen',
      'count.reps.one': '{n} Vertriebspartner',
      'count.reps.other': '{n} Vertriebspartner',
      'toast.langDe': 'Sprache: Deutsch',
      'toast.langEs': 'Idioma: español',
      'err.generic': 'Etwas ist schiefgelaufen. Bitte erneut versuchen.',
    },
  });
  document.title = TL.i18n.t('app.title');
})();
